### ISSUE TITLE
facter err with pe 2016.4.2

### ISSUE THREAD

**Issue by sye1774** [dylanratcliffe/windows_disk_facts#13]
When implementing this module, I am receiving the following facter error with windows 6.1.7601
======
Facter | error while resolving custom fact "partitions": A JSON text must at least contain two octets!
-- | --
err | Puppet | Failure waiting for PowerShell process 7288 to start pipe server
err | /Stage[main]/Dtnafacts/Exec[create-dtnafacts]/returns | change from notrun to 0 failed: Failure waiting for PowerShell process 7288 to start pipe server
err | /Stage[main]/Domain_membership/Exec[join_domain] | Could not evaluate: Failure waiting for PowerShell process 5804 to start pipe server
====

**Comment by njohnso** [comment]
We are also seeing this error.  It is not on all Windows servers. @dylanratcliffe do you have any idea what might be the cause of this problem?

**Comment by rmc47** [comment]
@njohnso are you seeing it on Server 2008 / 2008 R2? If so, the `Get-Partitions` cmdlet isn't valid, I think. PR #14 should fix it.

**Comment by JasonMcMahan** [comment]
You are right @rmc47 i fat fingered the partition variable. I created a pr #15 but @dylanratcliffe hasnt merged it yet. Sorry for the mistake.

**Comment by dylanratcliffe** [comment]
Hey guys sorry for the neglect here #15 is merged and released in `0.2.5`
