### ISSUE TITLE
Windows 2008: A JSON text must at least contain 2 octets

### ISSUE THREAD

**Issue by natemccurdy** [dylanratcliffe/windows_disk_facts#4]
On Windows 2008, I see this error message:

```
C:\Users\Administrator>puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Facter: error while resolving custom fact "disks": A JSON text must at least contain two octets!
Error: Facter: error while resolving custom fact "drives": A JSON text must at least contain two octets!
Error: Facter: error while resolving custom fact "partitions": A JSON text must at least contain two octets!
Info: Caching catalog for win2008-agent
Info: Applying configuration version '1463090046'
Notice: Applied catalog in 0.50 seconds
```

Some node info:

```
C:\Users\Administrator>facter os
{
  architecture => "x64",
  family => "windows",
  hardware => "x86_64",
  name => "windows",
  release => {
    full => "2008 R2",
    major => "2008 R2"
  },
  windows => {
    system32 => "C:\Windows\system32"
  }
}

C:\Users\Administrator>puppet --version
4.4.2
```

**Comment by natemccurdy** [comment]
Turns out its a Powershell version issue, not a Windows version issue:

```
C:\Users\Administrator>powershell.exe -Command "Get-Disk | select *  -ExcludeProperty CimClass,CimInstanceProperties,CimSystemProperties | ConvertTo-Json -Depth 999 -Compress"
The term 'Get-Disk' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and t
ry again.
At line:1 char:9
+ Get-Disk <<<<  | select *  -ExcludeProperty CimClass,CimInstanceProperties,CimSystemProperties | ConvertTo-Json -Depth 999 -Compress
    + CategoryInfo          : ObjectNotFound: (Get-Disk:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


C:\Users\Administrator>powershell
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

Powershell 2.0 does not have the `Get-Disk` cmdlet.

**Comment by JasonMcMahan** [comment]
Good day,
As this is a powershell issue, but we need to ensure it runs on all other machines.
What would people suggest?
Run an exec to retrieve powershell version then perform a conditional that is it is under powershell 3.3 ignore otherwise load the class?

It would be great to add it to the module that if it is below 3.3 it simply doesn't load instead of the Json error. Thank you and thoughts?

**Comment by GerbenWelter** [comment]
@natemccurdy @JasonMcMahan It *is* a Windows version issue. Even Windows 2008 with Powershell 4.0 throws the JSON error. The Technet documentation for Get-Disk confirms it implicitly:

[https://technet.microsoft.com/en-us/library/hh848657.aspx](url)

There's no section for 2008 (R2).

**Comment by covidium** [comment]
The same behavior is noticed on Windows 2016 Standard with Powershell 5.1 where beside the 2 octets needed, the max depth has been decreased to max 100.

PS C:\Users\o.calbajos> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
5      1      14393  693

PS C:\Users\o.calbajos> Get-Disk | select *  -ExcludeProperty CimClass,CimInstanceProperties,CimSystemProperties | ConvertTo-Json -Depth 999 -Compress
ConvertTo-Json : The maximum depth allowed for serialization is 100.
At line:1 char:92

PS C:\Users\o.calbajos> puppet agent -t
...
Error: Facter: error while resolving custom fact "disks": A JSON text must at least contain two octets!
Error: Facter: error while resolving custom fact "drives": A JSON text must at least contain two octets!
Error: Facter: error while resolving custom fact "partitions": A JSON text must at least contain two octets!

**Comment by covidium** [comment]
In order to solve this I've created depth variable based on the OS version and rescued the JSON.parse

  if :kernelversion == '6.4.9600'
    depth = '999'
  elsif :kernelversion == '10.0.14393'
    depth = '100'
  else
    depth = '999'
  end

[truncated] = JSON.parse(Facter::Core::Execution.exec("powershell.exe -Command ...[truncated]... ConvertTo-Json -Depth #{depth} -Compress\"")) rescue []

Should I create a pull request?

**Comment by natemccurdy** [comment]
@covidium Yes, please make a pull request 👍

**Comment by covidium** [comment]
@natemccurdy done
